.e2e-test-template:
  image: ${CI_REGISTRY}/${CI_PROJECT_PATH}/aval:${CI_COMMIT_REF_NAME}
  variables:
    TARGET_BUILD_TYPE: "nightly"
    AVAL_VERBOSE: "true"
  script:
    - /usr/local/bin/entrypoint.sh "docker run -e SOC_UDT=$SOC_UDT --privileged --pid host
      -v /var/run/docker.sock:/var/run/docker.sock -v /home/torizon:/home/torizon
      ${CI_REGISTRY}/${CI_PROJECT_PATH}/aval-e2e-tests:${CI_COMMIT_REF_NAME} /suites/run-tests.sh"
      --report /home/torizon/report.xml report.xml --before "docker system prune --all"
  artifacts:
    when: always
    reports:
      junit: report.xml
  needs:
    - unit-test

e2e-test-imx8mp-nightly:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "imx8mp"
    TARGET_BUILD_TYPE: "nightly"

e2e-test-imx8mm-nightly:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "imx8mm"
    TARGET_BUILD_TYPE: "nightly"

e2e-test-am62-nightly:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "am62"
    TARGET_BUILD_TYPE: "nightly"

e2e-test-imx8x-nightly:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "imx8x"
    TARGET_BUILD_TYPE: "nightly"

e2e-test-imx7-nightly:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "imx7"
    TARGET_BUILD_TYPE: "nightly"

e2e-test-imx6-nightly:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "imx6"
    TARGET_BUILD_TYPE: "nightly"

e2e-test-imx8mp-release:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "imx8mp"
    TARGET_BUILD_TYPE: "release"

e2e-test-imx8mm-release:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "imx8mm"
    TARGET_BUILD_TYPE: "release"

e2e-test-am62-release:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "am62"
    TARGET_BUILD_TYPE: "release"

e2e-test-imx8x-release:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "imx8x"
    TARGET_BUILD_TYPE: "release"

e2e-test-imx7-release:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "imx7"
    TARGET_BUILD_TYPE: "release"

e2e-test-imx6-release:
  extends: .e2e-test-template
  variables:
    SOC_UDT: "imx6"
    TARGET_BUILD_TYPE: "release"
